### ISSUE TITLE
would you please add a visiting stats banner at the most left bottom ?

### ISSUE THREAD

**Issue by ClarkThan** [AmazingRise/hugo-theme-diary#142]
I mean looks like this snapchat
<img width="766" alt="image" src="https://user-images.githubusercontent.com/8733905/217168675-9b14af05-9ab6-4e17-a548-12d5f4a97717.png">

**Comment by AmazingRise** [comment]
Hi ClarkThan,
Try [busuanzi](https://busuanzi.ibruce.info/) or [Waline](https://waline.js.org/en/guide/client/pageview.html#using-with-comment).

For busuanzi, you can append its code to [`layouts/partials/copyright.html`](https://github.com/AmazingRise/hugo-theme-diary/blob/main/layouts/partials/copyright.html)(it is the de facto global footer). 

For Waline, read the [guide](https://waline.js.org/en/guide/client/pageview.html#using-with-comment). Since we have integrated Waline, so you can find its configuration here:
https://github.com/AmazingRise/hugo-theme-diary/blob/bad0d28ed269fe2d7ea3c6e252dbaedc8fd4c74e/layouts/partials/comment.html#L66
Please add `pageview: true` to its configuration, and add pageview code to `copyright.html`:
```html
Pageviews: <i class="waline-pageview-count" data-path="{{ .Page.RelPermalink }}"></i>
```

**Comment by ClarkThan** [comment]
> Hi ClarkThan, Try [busuanzi](https://busuanzi.ibruce.info/) or [Waline](https://waline.js.org/en/guide/client/pageview.html#using-with-comment).
> 
> For busuanzi, you can append its code to [`layouts/partials/copyright.html`](https://github.com/AmazingRise/hugo-theme-diary/blob/main/layouts/partials/copyright.html)(it's the de facto global footer).
> 
> For Waline, read the [guide](https://waline.js.org/en/guide/client/pageview.html#using-with-comment). Since we have integrated Waline, you can find its configuration here:
> 
> https://github.com/AmazingRise/hugo-theme-diary/blob/bad0d28ed269fe2d7ea3c6e252dbaedc8fd4c74e/layouts/partials/comment.html#L66
> 
> 
> Please add `pageview: true` to its configuration, and add pageview code to `copyright.html`:
> ```
> Pageviews: <i class="waline-pageview-count" data-path="{{ .Page.RelPermalink }}"></i>
> ```

thanks, appreciate your solutions
