### ISSUE TITLE
Catalog auto scroll with content

### ISSUE THREAD

**Issue by Linon419** [AmazingRise/hugo-theme-diary#17]
**Describe the bug**
目录只能显示第一页，不能跟随文章自动下滑，只能手动
**To Reproduce**
当标题过多时
**Screenshots**
<img width="988" alt="Screen Shot 2020-04-07 at 9 25 30 AM" src="https://user-images.githubusercontent.com/29937602/78614461-f9941f00-78b1-11ea-803c-ac4ed468fce0.png">

**Comment by AmazingRise** [comment]
首先，感谢你的建议。
但是我还有一些疑问：
1. 目前的版本里面已经带了ToC的滚动条（since #11 ），如图所示
![图片](https://user-images.githubusercontent.com/8315221/78620995-0a459480-78b4-11ea-8098-b23567046d2d.png)
你现在用的我猜可能是旧版的，建议更新一下你的本地代码。
（这个功能已经在master分支里面了，testing分支是目前正在开发的深色模式功能，与这个无关）
2.  我顺便参考了一下[其他主题的实现](https://github.com/ahonn/hexo-theme-even/issues/120)，我个人觉得引入目录自动折叠（在Project 1.2.0中的"Refactor of ToC"，目标是做成类似于 Hexo Theme Next 的那种）要略微优于自动滚动的方案。但是由于本人近期实在是繁忙，这个功能要是引入的话可能也要至少一个月了，敬请原谅。

**Comment by Linon419** [comment]
我感觉Next那种方式很棒，谢谢你。

**Comment by AmazingRise** [comment]
现在这个功能已经发布到 testing 分支了。
可以在本地帮忙测试一下吗？感谢。
如果没有bug的话，过段时间推到 master 分支。

这是我的博客，目前是 testing 的版本。
https://amazingrise.net/2019/10/28/howto-use-spyder-debugger/

**Comment by wych42** [comment]
确认可以用。

https://yuchi.me/post/deploy-production-ready-elk-cluster-with-docker/

**Comment by AmazingRise** [comment]
> 确认可以用。
> 
> https://yuchi.me/post/deploy-production-ready-elk-cluster-with-docker/

感谢你的测试。

目前已经推送到master分支，刚才对性能略有优化，请拉取最新的代码。

再次感谢楼上两位的反馈。
