### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by motilalmeher** [AmazingRise/hugo-theme-diary#31]
Can you add an about page? It will be a good enhancement. 
And how to Put a logo Beside title of the page.

**Comment by AmazingRise** [comment]
Thanks for your feedback.
And to keep this theme simple, I won't add such features. Because I tend to leave the freedom for users. You can create your own about page in your own style.

You can do this by adding custom HTML contents, too.
See what I answered here:
https://github.com/AmazingRise/hugo-theme-diary/issues/30#issuecomment-622189433
