### ISSUE TITLE
image margin

### ISSUE THREAD

**Issue by helloqb** [AmazingRise/hugo-theme-diary#56]
在使用 markdown 原生的写法时若上下空一行，则生成的文章中图片和文字上下会有间隔，但是使用 html 格式，则生成的文章中图片下方和文字缺少间隔，不够美观。

**编写如下**
```markdown
你好你好你好你好你好你好你好你好你好你好。你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好。你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好。

![AragakiYui](https://i.loli.net/2020/08/06/YwFuaOm9n3zADvX.png)

你好你好你好你你好你好。你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好。你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好。

<img src="https://i.loli.net/2020/08/06/YwFuaOm9n3zADvX.png"/>

你好你好你好你好你好你好你好你好你好你好你好你好你好。你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好。你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好你好。
```
**生成文章如下**

![image.png](https://i.loli.net/2020/08/06/EArNGVIsYTwpex5.png)

由于个人文章经常会用到规定图片高度或者居中，所有希望能够解决 html 情况下的bug

**Comment by AmazingRise** [comment]
Hi, helloqb.
1. Please read wiki carefully before posting. Shortcode for inserting figure is implemented [here](https://github.com/AmazingRise/hugo-theme-diary/wiki/Inserting-Figures). I've implemented sizing and alignment.
2. This issue is caused by incorrect usage of HTML. Please don't forget to add a `<p></p>` before and after a paragraph when using HTML, or the margins will not be shown.

1. 请在提问前认真阅读维基。关于插图的Shortcode已经在[这里](https://github.com/AmazingRise/hugo-theme-diary/wiki/Inserting-Figures)实现。这个功能可以调整图片的尺寸和对齐方式。
2. 这个问题是 HTML 使用不正确造成的。请不要忘记在使用HTML时，文段前后须插入`<p></p>`。否则不会生成边距。

For further support, please post your question here.
Thanks for your feedback.

如果还有问题，欢迎在此跟帖。
感谢你的反馈！

**Comment by helloqb** [comment]
@AmazingRise 
感谢回复。
1. Shortcode 方式我怕会导致文章的兼容性和移植性降低，比如编辑器中的 markdown 预览插件就会失效。
2. `<p></p>` 是个不错的补救方法，不过之前的文章都得重新加一下了。

**Comment by AmazingRise** [comment]
> @AmazingRise
> 感谢回复。
> 
> 1. Shortcode 方式我怕会导致文章的兼容性和移植性降低，比如编辑器中的 markdown 预览插件就会失效。
> 2. `<p></p>` 是个不错的补救方法，不过之前的文章都得重新加一下了。

其实还有一个方法，就是在CSS中对img元素加边距。例如：

```css
img {
    margin: 10px;
}
```

但我个人是不推荐的。因为标准 Markdown 渲染时默认会在一段文字上面加`<p>`，如果写 HTML 代码会破坏这个转换。
